import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
opacity = 0.75
padding.x = 10
padding.y = 10

decorations = "Buttonless"

[font]
normal.family = "Hack Nerd Font Mono"

#regular
size = 24

